"""
Unit tests for DNS reachability validations.

Tests for DnsReachabilityCollector and VerifyDnsReachability validators.
"""

import json
from unittest.mock import Mock

import pytest

from in_cluster_checks.rules.network.dns_validations import DnsReachabilityCollector, VerifyDnsReachability
from tests.pytest_tools.test_data_collector_base import DataCollectorScenarioParams, DataCollectorTestBase
from tests.pytest_tools.test_operator_base import CmdOutput
from tests.pytest_tools.test_rule_base import RuleScenarioParams, RuleTestBase


class TestDnsReachabilityCollector(DataCollectorTestBase):
    """Tests for DnsReachabilityCollector data collector."""

    tested_type = DnsReachabilityCollector

    # Sample resolv.conf with nameservers
    resolv_conf_standard = """# Generated by NetworkManager
search cluster.local
nameserver 192.168.1.1
nameserver 8.8.8.8
"""

    scenarios = [
        DataCollectorScenarioParams(
            "resolv_conf_dns_servers_reachable",
            {
                "cat /etc/resolv.conf": CmdOutput(resolv_conf_standard),
                "ping -c 3 -W 2 192.168.1.1": CmdOutput(""),
                "ping -c 3 -W 2 8.8.8.8": CmdOutput(""),
            },
            scenario_res={
                "source": "/etc/resolv.conf",
                "reachable": ["192.168.1.1", "8.8.8.8"],
                "unreachable": [],
            },
            tested_object_mock_dict={
                "file_utils.is_file_exist": Mock(return_value=True),
            },
        ),
        DataCollectorScenarioParams(
            "resolv_conf_dns_servers_some_unreachable",
            {
                "cat /etc/resolv.conf": CmdOutput(resolv_conf_standard),
                "ping -c 3 -W 2 192.168.1.1": CmdOutput(""),
                "ping -c 3 -W 2 8.8.8.8": CmdOutput("", return_code=1),
            },
            scenario_res={
                "source": "/etc/resolv.conf",
                "reachable": ["192.168.1.1"],
                "unreachable": ["8.8.8.8"],
            },
            tested_object_mock_dict={
                "file_utils.is_file_exist": Mock(return_value=True),
            },
        ),
    ]

    @pytest.mark.parametrize("scenario_params", scenarios)
    def test_collect_data(self, scenario_params, tested_object):
        DataCollectorTestBase.test_collect_data(self, scenario_params, tested_object)


class TestVerifyDnsReachability(RuleTestBase):
    """Tests for VerifyDnsReachability orchestrator validator."""

    tested_type = VerifyDnsReachability

    # DNS operator config with upstream resolvers
    dns_config_with_upstreams = json.dumps(
        {
            "spec": {
                "upstreamResolvers": {
                    "upstreams": [
                        {"type": "Network", "address": "192.168.1.1", "port": 53},
                        {"type": "Network", "address": "8.8.8.8", "port": 53},
                    ]
                }
            }
        }
    )

    # DNS operator config without upstream resolvers
    dns_config_no_upstreams = json.dumps({"spec": {}})

    @pytest.fixture
    def tested_object(self):
        """Create tested object (OrchestratorRule)."""
        tested_obj = self.tested_type(host_executor=Mock())
        # Mock oc_api
        tested_obj.oc_api = Mock()
        return tested_obj

    scenario_passed = [
        RuleScenarioParams(
            scenario_title="upstream_resolvers_all_reachable",
            tested_object_mock_dict={
                "oc_api.run_oc_command": Mock(return_value=(0, dns_config_with_upstreams, "")),
                "run_data_collector": Mock(
                    return_value={
                        "node-1": {
                            "source": "cluster upstream resolvers",
                            "reachable": ["192.168.1.1", "8.8.8.8"],
                            "unreachable": [],
                        }
                    }
                ),
                "get_data_collector_exceptions": Mock(return_value={}),
            },
        ),
        RuleScenarioParams(
            scenario_title="no_upstreams_resolv_conf_reachable",
            tested_object_mock_dict={
                "oc_api.run_oc_command": Mock(return_value=(0, dns_config_no_upstreams, "")),
                "run_data_collector": Mock(
                    return_value={
                        "node-1": {"source": "/etc/resolv.conf", "reachable": ["192.168.1.1"], "unreachable": []},
                        "node-2": {"source": "/etc/resolv.conf", "reachable": ["192.168.1.1"], "unreachable": []},
                    }
                ),
                "get_data_collector_exceptions": Mock(return_value={}),
            },
        ),
    ]

    scenario_failed = [
        RuleScenarioParams(
            scenario_title="upstream_resolvers_unreachable",
            tested_object_mock_dict={
                "oc_api.run_oc_command": Mock(return_value=(0, dns_config_with_upstreams, "")),
                "run_data_collector": Mock(
                    return_value={
                        "node-1": {
                            "source": "cluster upstream resolvers",
                            "reachable": ["192.168.1.1"],
                            "unreachable": ["8.8.8.8"],
                        }
                    }
                ),
                "get_data_collector_exceptions": Mock(return_value={}),
            },
            failed_msg="Unreachable from one or more nodes (1):",
        ),
        RuleScenarioParams(
            scenario_title="no_dns_servers_found",
            tested_object_mock_dict={
                "oc_api.run_oc_command": Mock(return_value=(0, dns_config_no_upstreams, "")),
                "run_data_collector": Mock(return_value={}),
                "get_data_collector_exceptions": Mock(return_value={}),
            },
            failed_msg="No DNS servers found.",
        ),
        RuleScenarioParams(
            scenario_title="data_collection_failed",
            tested_object_mock_dict={
                "oc_api.run_oc_command": Mock(return_value=(0, dns_config_no_upstreams, "")),
                "run_data_collector": Mock(return_value={}),
                "get_data_collector_exceptions": Mock(return_value={"node-1": Exception("Connection failed")}),
            },
            failed_msg="Failed to test DNS reachability from 1 node(s): node-1.",
        ),
    ]

    @pytest.mark.parametrize("scenario_params", scenario_passed)
    def test_scenario_passed(self, scenario_params, tested_object):
        RuleTestBase.test_scenario_passed(self, scenario_params, tested_object)

    @pytest.mark.parametrize("scenario_params", scenario_failed)
    def test_scenario_failed(self, scenario_params, tested_object):
        RuleTestBase.test_scenario_failed(self, scenario_params, tested_object)
