import json
from unittest.mock import Mock

import pytest

from in_cluster_checks.rules.network.dns_validations import (
    DnsOperatorConfigCollector,
    VerifyDnsReachability,
)
from tests.pytest_tools.test_data_collector_base import DataCollectorScenarioParams, DataCollectorTestBase
from tests.pytest_tools.test_operator_base import CmdOutput
from tests.pytest_tools.test_rule_base import RuleScenarioParams, RuleTestBase


class TestDnsOperatorConfigCollector(DataCollectorTestBase):
    """Tests for DnsOperatorConfigCollector data collector."""

    tested_type = DnsOperatorConfigCollector

    # DNS operator config with upstream resolvers
    dns_config_with_upstreams = json.dumps(
        {
            "spec": {
                "upstreamResolvers": {
                    "upstreams": [
                        {"type": "Network", "address": "192.168.1.1"},
                        {"type": "Network", "address": "8.8.8.8"},
                    ]
                }
            }
        }
    )

    # DNS operator config without upstream resolvers
    dns_config_no_upstreams = json.dumps({"spec": {}})

    scenarios = [
        DataCollectorScenarioParams(
            "dns_operator_with_upstreams",
            {},
            scenario_res=["192.168.1.1", "8.8.8.8"],
            oc_cmd_output_dict={
                ("get", ("dns.operator.openshift.io/cluster", "-o", "json")): CmdOutput(
                    dns_config_with_upstreams
                )
            },
        ),
        DataCollectorScenarioParams(
            "dns_operator_no_upstreams",
            {},
            scenario_res=[],
            oc_cmd_output_dict={
                ("get", ("dns.operator.openshift.io/cluster", "-o", "json")): CmdOutput(dns_config_no_upstreams)
            },
        ),
        DataCollectorScenarioParams(
            "dns_operator_not_found",
            {},
            scenario_res=[],
            oc_cmd_output_dict={
                ("get", ("dns.operator.openshift.io/cluster", "-o", "json")): CmdOutput(
                    "", return_code=1, err="NotFound"
                )
            },
        ),
    ]

    @pytest.mark.parametrize("scenario_params", scenarios)
    def test_collect_data(self, scenario_params, tested_object):
        """Test collect_data returns DNS operator upstream servers."""
        self._init_data_collector_object(tested_object, scenario_params)
        result = tested_object.collect_data()
        assert result == scenario_params.scenario_res, (
            f"Data collector result mismatch for scenario: {scenario_params.scenario_title}\n"
            f"Expected: {scenario_params.scenario_res}\n"
            f"Got: {result}"
        )


class TestVerifyDnsReachability(RuleTestBase):
    """Tests for VerifyDnsReachability rule."""

    tested_type = VerifyDnsReachability

    resolv_conf_content = """# Generated by NetworkManager
search cluster.local
nameserver 192.168.1.1
nameserver 8.8.8.8
"""

    scenario_passed = [
        RuleScenarioParams(
            scenario_title="all_dns_servers_reachable_from_operator",
            tested_object_mock_dict={
                "get_data_from_collector": Mock(return_value=["192.168.1.1", "8.8.8.8"]),
            },
            cmd_input_output_dict={
                "ls /etc/resolv.conf": CmdOutput("/etc/resolv.conf"),
                "cat /etc/resolv.conf": CmdOutput("search openshift.svc.cluster.local\n"),
                "dig +short +time=2 +tries=1 @192.168.1.1 openshift.svc.cluster.local": CmdOutput("10.0.0.1\n"),
                "dig +short +time=2 +tries=1 @8.8.8.8 openshift.svc.cluster.local": CmdOutput("10.0.0.1\n"),
            },
        ),
        RuleScenarioParams(
            scenario_title="all_dns_servers_reachable_from_resolv_conf",
            tested_object_mock_dict={
                "get_data_from_collector": Mock(return_value=[]),
            },
            cmd_input_output_dict={
                "ls /etc/resolv.conf": CmdOutput("/etc/resolv.conf"),
                "cat /etc/resolv.conf": CmdOutput(resolv_conf_content),
                "dig +short +time=2 +tries=1 @192.168.1.1 cluster.local": CmdOutput("10.0.0.1\n"),
                "dig +short +time=2 +tries=1 @8.8.8.8 cluster.local": CmdOutput("10.0.0.1\n"),
            },
        ),
    ]

    scenario_failed = [
        RuleScenarioParams(
            scenario_title="some_dns_servers_unreachable",
            tested_object_mock_dict={
                "get_data_from_collector": Mock(return_value=["192.168.1.1", "8.8.8.8"]),
            },
            cmd_input_output_dict={
                "ls /etc/resolv.conf": CmdOutput("/etc/resolv.conf"),
                "cat /etc/resolv.conf": CmdOutput("search openshift.svc.cluster.local\n"),
                "dig +short +time=2 +tries=1 @192.168.1.1 openshift.svc.cluster.local": CmdOutput("10.0.0.1\n"),
                "dig +short +time=2 +tries=1 @8.8.8.8 openshift.svc.cluster.local": CmdOutput("", return_code=1),
            },
            failed_msg="DNS servers from DNS operator upstream resolvers unreachable: 8.8.8.8",
        ),
        RuleScenarioParams(
            scenario_title="no_dns_servers_found",
            tested_object_mock_dict={
                "get_data_from_collector": Mock(return_value=[]),
            },
            cmd_input_output_dict={
                "ls /etc/resolv.conf": CmdOutput("", return_code=2),  # File not found
            },
            failed_msg="No DNS servers found",
        ),
    ]

    @pytest.mark.parametrize("scenario_params", scenario_passed)
    def test_scenario_passed(self, scenario_params, tested_object):
        RuleTestBase.test_scenario_passed(self, scenario_params, tested_object)

    @pytest.mark.parametrize("scenario_params", scenario_failed)
    def test_scenario_failed(self, scenario_params, tested_object):
        RuleTestBase.test_scenario_failed(self, scenario_params, tested_object)
